version: '3'
services:
  db:
    image: postgres
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rake db:create && rake db:migrate && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
