version: '3'
services:
  db:
    image: postgres
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "RAILS_ENV=production rake db:create && RAILS_ENV=production rake db:migrate && RAILS_ENV=production rake assets:precompile && bundle exec rails s -e production -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - db
